export enum QueryKeys {
  messages = 'messages',
  sharedMessages = 'sharedMessages',
  sharedLinks = 'sharedLinks',
  allConversations = 'allConversations',
  archivedConversations = 'archivedConversations',
  searchConversations = 'searchConversations',
  conversation = 'conversation',
  searchEnabled = 'searchEnabled',
  user = 'user',
  name = 'name', // user key name
  models = 'models',
  balance = 'balance',
  endpoints = 'endpoints',
  searchResults = 'searchResults',
  tokenCount = 'tokenCount',
  availablePlugins = 'availablePlugins',
  startupConfig = 'startupConfig',
  agents = 'agents',
  agent = 'agent',
  files = 'files',
  fileConfig = 'fileConfig',
  toolAuth = 'toolAuth',
  toolCalls = 'toolCalls',
  agentDocs = 'agentDocs',
  fileDownload = 'fileDownload',
  filePreview = 'filePreview',
  voices = 'voices',
  customConfigSpeech = 'customConfigSpeech',
  categories = 'categories',
  roles = 'roles',
  rolesList = 'rolesList',
  conversationTags = 'conversationTags',
  health = 'health',
  userTerms = 'userTerms',
  banner = 'banner',
  /* Memories */
  memories = 'memories',
  principalSearch = 'principalSearch',
  accessRoles = 'accessRoles',
  resourcePermissions = 'resourcePermissions',
  effectivePermissions = 'effectivePermissions',
  graphToken = 'graphToken',
  /* Active Jobs */
  activeJobs = 'activeJobs',
  /* Agent API Keys */
  agentApiKeys = 'agentApiKeys',
  /* Skills */
  skills = 'skills',
  skill = 'skill',
  skillFiles = 'skillFiles',
  skillFileContent = 'skillFileContent',
  /* Skill tree (phase 2 — filesystem-style node view) */
  skillTree = 'skillTree',
  skillNodeContent = 'skillNodeContent',
  /* Skill favorites (star a skill in the sidebar) */
  skillFavorites = 'skillFavorites',
  /* Per-user skill active/inactive overrides */
  skillStates = 'skillStates',
  /* General user favorites */
  favorites = 'favorites',
  preferences = 'preferences',
  preferenceIngredients = 'preferenceIngredients',
  protectedImage = 'protectedImage',
  cookingDraft = 'cookingDraft',
  cookingDocuments = 'cookingDocuments',
  cookingSession = 'cookingSession',
  recipes = 'recipes',
  recipe = 'recipe',
}

export enum MutationKeys {
  createAgentApiKey = 'createAgentApiKey',
  deleteAgentApiKey = 'deleteAgentApiKey',
  fileUpload = 'fileUpload',
  fileDelete = 'fileDelete',
  loginUser = 'loginUser',
  logoutUser = 'logoutUser',
  refreshToken = 'refreshToken',
  avatarUpload = 'avatarUpload',
  speechToText = 'speechToText',
  textToSpeech = 'textToSpeech',
  deleteUser = 'deleteUser',
  updateRole = 'updateRole',
  enableTwoFactor = 'enableTwoFactor',
  verifyTwoFactor = 'verifyTwoFactor',
  updateMemoryPreferences = 'updateMemoryPreferences',
  /* Skill mutations from the original UI PR — tree/node operations are
   * phase 2 and currently stubbed in the data-service layer. */
  createSkillNode = 'createSkillNode',
  updateSkillNode = 'updateSkillNode',
  deleteSkillNode = 'deleteSkillNode',
  updateSkillNodeContent = 'updateSkillNodeContent',
  updatePreferences = 'updatePreferences',
  preferencesChat = 'preferencesChat',
  resolvePreferenceIngredient = 'resolvePreferenceIngredient',
  generateCookingDraft = 'generateCookingDraft',
  updateCookingDraft = 'updateCookingDraft',
  createCookingDocument = 'createCookingDocument',
  updateCookingDocument = 'updateCookingDocument',
  selectCookingDocument = 'selectCookingDocument',
  deleteCookingDocument = 'deleteCookingDocument',
  startCookingSession = 'startCookingSession',
  appendCookingSessionEvent = 'appendCookingSessionEvent',
  completeCookingSession = 'completeCookingSession',
  saveRecipe = 'saveRecipe',
  updateSavedRecipe = 'updateSavedRecipe',
  deleteSavedRecipe = 'deleteSavedRecipe',
}
